
language: node_js
node_js:
  - "11"

# 只监听 source 分支的改动
branches:
  only:
  - source

# 缓存依赖，节省持续集成时间
cache:
  yarn: true
  directories:
    - node_modules
    # - themes

before_install:
# 解密 RSA 私钥并设置为本机 ssh 私钥
- openssl aes-256-cbc -K $encrypted_9aab6d74e2ca_key -iv $encrypted_9aab6d74e2ca_iv 
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
# 修改本机 ssh 配置，防止秘钥认证过程影响自动部署
- mv -fv .travis/ssh-config ~/.ssh/config
- git config --global user.name "sbmzhcn"
- git config --global user.email "sbmzhcn@gmail.com"
# 赋予自动部署脚本可执行权限
- chmod +x .travis/deploy.sh

install:
# 安装 Hexo 及其依赖
- yarn
# 当 Travis 文件缓存不存在时，从 Gitee 私有仓库 clone 主题
#- if [ ! -d "themes/next" ]; then git clone git@github.com:sbmzhcn/hexo-theme-next.git themes/next; fi

script:
# 更新ALGOLIA索引
- export HEXO_ALGOLIA_INDEXING_KEY=${HEXO_ALGOLIA_INDEXING_KEY}
- node_modules/.bin/hexo algolia
# 生成静态页面
- node_modules/.bin/hexo clean
- node_modules/.bin/hexo generate
- gulp

after_success:
# 部署到 GitHub Pages 和 VPS
- .travis/deploy.sh

addons:
  ssh_know_hosts:
  - github.com
  - love4026.org

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    # not support ${qq} can use travis encrypt - secure: ""
    - secure: "N1eZ8JMOijc09xG2rHT9MirXIIFZEs6RCqcvFEPw4MWuc7Lhk/PEcezaZGXZezm8Hs1OCRg+K6ldUU//EPBNIY25Afi+JdvHPsDODkQ6XnCfYADxthaNP5ZRo9Fqbp1XW2gUlCrvB63/McoLJ9wyA/l7Vh/JIIzQXZhKNwN0pkrLnS/f1Jh7jd3eg8Tq7N5SWx+WwC/tgHhHIDG1XHEBq8pLjulvxhMEkx1jlhvJhojEJTI2BvBM7RXxZi1zEAbRG4N/5JmhO5tY63wlRIr5gRjqwSTnOrQPW7+qKPz/0iEbsJ+/2lxNC6rjeRzB/+DWURRXF+HokxZ0Wj0KFRwqJzW3aQ/nG0GHx976cYG05/mX5Zjz4ftYz0VpggMqiDySPW7h2yPBDAlE4oE+8ZTuTafHwNrXVC4s55gJGNJzZ5RejeBCAy2FHTWtXoatfP3DyjjIFgJYsHGKBVEzd7FZEWkkLzQFAdAivD/O4YOfun5cTa1G85+T3DwFjfP9fPp0bxXT2+B6MGLBHe97SYJtrwcxDCD9Ug94Cxby9UwQxHzCbPPv0gMjsyKR9BLFIp/LasruskXEEDOV7qLLyFev18/dSSFlu9OLUX6aBq5TxpVjYMTKJfkvx/QeNXL2Y0PogKJm9DsyvYqfmrQFPqU4Cepbbs2aJoE7ymMl+70ARvo="
    - love4026@gmail.com
  on_success: change
  on_failure: always